version: '3'

networks:
  laravel:

services:
  app:
    build:
      context: ./dockerfiles
      dockerfile: nginx.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html:delegated
    depends_on:
      - php
      - redis
      - database
      - mailhog
    networks:
      - laravel
    container_name: "${PROJECT_NAME}-app-service"

  database: # --- choose any name you prefer, name of service
    image: postgres:14-alpine # --- choose any tag you need
    restart: unless-stopped
    tty: true
    container_name: "${PROJECT_NAME}-database-service"
    ports:
      - "${SQL_PORT}:${SQL_PORT}"
    environment:
      #MYSQL_DATABASE: ${SQL_DATABASE} #
      #MYSQL_USER: ${SQL_USER} #
      #MYSQL_PASSWORD: ${SQL_PASSWORD} #
      #MYSQL_ROOT_PASSWORD: ${SQL_ROOT_PASSWORD} #
      POSTGRES_DB: "${SQL_DATABASE}" #
      POSTGRES_USER: "${SQL_USER}" #
      POSTGRES_PASSWORD: "${SQL_PASSWORD}" #
      SERVICE_TAGS: dev
      SERVICE_NAME: database
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - laravel

  php:
    container_name: "${PROJECT_NAME}-php-service"
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    # "user" value will determine the default user used when accessing the docker container
    # user: 'www-data:www-data'
    ports:
      - "9000:9000"
    volumes:
      - ./src:/var/www/html:delegated
    networks:
      - laravel

  redis:
    container_name: "${PROJECT_NAME}-redis-service"
    image: redis:alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - laravel

  composer:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    volumes:
      - ./src:/var/www/html
    depends_on:
      - php
    entrypoint: [ 'composer', '--ignore-platform-reqs' ]
    networks:
      - laravel

  npm:
    image: node:current-alpine
    volumes:
      - ./src:/var/www/html
    ports:
      - "3000:3000"
      - "3001:3001"
      - "5173:5173"
    working_dir: /var/www/html
    entrypoint: [ 'npm' ]
    networks:
      - laravel

  artisan:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    volumes:
      - ./src:/var/www/html:delegated
    depends_on:
      - database
    entrypoint: [ 'php', '/var/www/html/artisan' ]
    networks:
      - laravel

  mailhog:
    container_name: "${PROJECT_NAME}-mailhog-service"
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - laravel
